export default {
  iss: {
    pub: 'GCNWL3VEQKRBI4AUTO7O6MI27DVL7QXBYBK2XUNSMDNKBZNHC5RCFOWM',
    priv: 'SBKJEJEL43WUVEJSIDSE75DKMNECGWBFDU64RWSKA6RBLVJEOGEDRZU7'
  },
  dis: {
    pub: 'GDUZ7SJD7MGHZLJPOYCVRCYFIZ47J2ESGXA44X5LSUGGT3FV5FEGD7D2',
    priv: 'SAXXTZBMYFB3I2MTXRG6C5C5TZJL7EGMSREZCQ24YK2NEN7VDEQFTDVR'
  },
  stellar: {
    pub: 'GDUZ7SJD7MGHZLJPOYCVRCYFIZ47J2ESGXA44X5LSUGGT3FV5FEGD7D2',
    priv: 'SAXXTZBMYFB3I2MTXRG6C5C5TZJL7EGMSREZCQ24YK2NEN7VDEQFTDVR'
  },
  asset: {
    code: 'KAREL'
  },
  testnet: true
}

// Stellar source account is same as EVER source account in this example
// Remove priv keys and input them from cmd via read package